### ISSUE TITLE
!help Need Help regarding the signaling server 

### ISSUE THREAD

**Issue by Avinash-Gahlowt** [coder-with-a-bushido/simple-webrtc-react-app#2]
I just wanted help in deployment of signaling server, I have a signaling server in python which runs on a localhost "127.0.0.1:8443" and a html>JavaScript file which I open in browser manually then the get connected with each other but I want the same scenario over the internet. That is I want a link over the internet as your app has so I need to do the same functionality. I'm unable to host the python file over internet and kindly help me with that. It's Urgent Please Help Out....

**Comment by coder-with-a-bushido** [comment]
you can checkout [Railway](https://railway.app/) or [Render](https://render.com/)

**Comment by coder-with-a-bushido** [comment]
Closing this as its not really an issue with the repo itself
